apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-statefulset
  namespace: prometheus-app
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: "nginx"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534         # user: nobody
        runAsGroup: 65534
        fsGroup: 65534           # user: nobody is going to own all volumes attached to pod
      terminationGracePeriodSeconds: 10
      containers:
      - name: prometheus
        image: prom/prometheus:v2.51.1
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: config-dir
          mountPath: /etc/prometheus/
        - name: prometheus-persistent-volume
          mountPath: /prometheus
      volumes:
      - name: config-dir
        configMap:
          name: prometheus-config-cm
  volumeClaimTemplates:
  - metadata:
      name: prometheus-persistent-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ceph-rbd"
      resources:
        requests:
          storage: 5Gi
