apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless-service
  namespace: prometheus-app
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    name: prometheus
  clusterIP: None
  selector:
    app: prometheus
